### ISSUE TITLE
,

### ISSUE THREAD

**Issue by alexisgrolot** [darylldoyle/svg-sanitizer#106]

**Comment by kubiqsk** [comment]
I don't think that your question has anything to do with this library...

Just google for `wp_remote_get` (https://developer.wordpress.org/reference/functions/wp_remote_get/)
read how to use it, or take a look in User Contributed Notes for code examples (https://developer.wordpress.org/reference/functions/wp_remote_get/#user-contributed-notes)

Same for `WP_Filesystem`... https://developer.wordpress.org/reference/functions/wp_filesystem/

Everything is pretty great documented and in these days you can also use ChatGPT, Gemini or Copilot to help you with some implementation, but that also requires you to check it properly as it often output some bullshit code.

I hope your plugin is a school project or a hobby one, because if you would like to offer your code to your clients or for public use, then you should not ask questions like this, because it means that there will be much more serious problems in your code. _#noHateJustAdvice_
