### ISSUE TITLE
Change the license type to MIT or to Apache 2.0 or to the double license GPL v2 + MIT or GPL v2 + Apache 2

### ISSUE THREAD

**Issue by redikultsevsilver** [darylldoyle/svg-sanitizer#56]
Hi @darylldoyle!

I hope everything is great.

We would like to use your library, however we are working on a non-open source software.
The current license (GPL v2) is blocking us from using the library.

Could you please consider changing the license to MIT or to Apache 2.0? 
Or perhaps having a double license like  GPL v2 + MIT or GPL v2 + Apache 2 would be fine for you?

In that case more software developers will be able to use the library.

**Comment by ohader** [comment]
In general, GPL does not disallow using corresponding software components in proprietary products - however, GPL ensures that free software stays free - thus, vendors are not allowed to restrict that freedom once it has been granted. That's the general idea...

Changing to Apache 2.0 would not be an option since it would lead to incompatibilities for current users (most of them compatible to GPLv2 or any later version). Thus, MIT seems to be the only remaining part.

In any way, to change the current license all contributors would have to agree to this license change, see https://www.gnu.org/licenses/gpl-faq.html#Consider

> **Consider this situation: 1) X releases V1 of a project under the GPL. 2) Y contributes to the development of V2 with changes and new code based on V1. 3) X wants to convert V2 to a non-GPL license. Does X need Y's permission?**
>
> Yes. Y was required to release its version under the GNU GPL, as a consequence of basing it on X's version V1. Nothing required Y to agree to any other license for its code. Therefore, X must get Y's permission before releasing that code under another license.

**Comment by Kooper** [comment]
Will introduction of LGPL be somewhat easier?
It will still guarantee that free software stays free and will not demand release of proprietary code which uses the library under GPL-compatible license.

**Comment by darylldoyle** [comment]
Hi All 👋 

Thanks for having this discussion.

I am a big believer in the GPL licence, unfortunately, that means that some people can't use this library in their own software without releasing it under the GPL. This is an unfortunate case, but this is an open-source library and I intend for it to stay that way.

If the GPL is incompatible with your licencing, I apologise for that, but I won't change the licence or release it under a dual licence.
